[package]
name = "client_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcproto-rs = "0.2.0"
craftio-rs = "0.1.0"
reqwest = "0.11"
ms_auth_mc = "0.2.0"
